//
// Generated file, do not edit! Created by opp_msgc 4.5 from messages/QueueLengthRequest.msg.
//

#ifndef _QUEUELENGTHREQUEST_M_H_
#define _QUEUELENGTHREQUEST_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/QueueLengthRequest.msg</tt> by opp_msgc.
 * <pre>
 * packet QueueLengthRequest {
 *     string moduleName;  
 *     int	gateID;         
 *     int outAddress;     
 * }
 * </pre>
 */
class QueueLengthRequest : public ::cPacket
{
  protected:
    opp_string moduleName_var;
    int gateID_var;
    int outAddress_var;

  private:
    void copy(const QueueLengthRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const QueueLengthRequest&);

  public:
    QueueLengthRequest(const char *name=NULL, int kind=0);
    QueueLengthRequest(const QueueLengthRequest& other);
    virtual ~QueueLengthRequest();
    QueueLengthRequest& operator=(const QueueLengthRequest& other);
    virtual QueueLengthRequest *dup() const {return new QueueLengthRequest(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getModuleName() const;
    virtual void setModuleName(const char * moduleName);
    virtual int getGateID() const;
    virtual void setGateID(int gateID);
    virtual int getOutAddress() const;
    virtual void setOutAddress(int outAddress);
};

inline void doPacking(cCommBuffer *b, QueueLengthRequest& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, QueueLengthRequest& obj) {obj.parsimUnpack(b);}


#endif // _QUEUELENGTHREQUEST_M_H_
